sudo: required
dist: trusty
cache: ccache

language:
  - c++
# - objective-c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - |
    ANALYZE=false
    DOC=false

matrix:
  include:
    os: linux
    compiler: clang
    env: ANALYZE=true DOC=true

branches:
  only:
  - master
  - branch-1.3
  - /^feature-.*/
  - /^fix-.*/
  - /^issue-.*/
  - /^str-.*/

before_script:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
       sudo apt-get update -q
       sudo apt-get install -y libxinerama-dev libxcursor-dev libasound2-dev libglew-dev
       sudo apt-get install -y doxygen
    elif [ $TRAVIS_OS_NAME == osx ]; then
      brew install ccache # need to install on macOS
      # brew install glew   # libGLEW not needed on macOS
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install doxygen
    fi

script:
  - |
   if [ $ANALYZE = "false" ]; then
     autoconf
     ./configure
     make
     mkdir cmake-build
     cd cmake-build
     cmake -G "Unix Makefiles" -D FLTK_BUILD_EXAMPLES=ON ..
     make
   else
     mkdir scan-build
     cd scan-build
     scan-build cmake -G "Unix Makefiles" -D FLTK_BUILD_EXAMPLES=ON ..
     scan-build -v make
   fi

after_success:
  - |
    if [ $DOC = "true" ]; then
      doxygen --version
      cd documentation
      make html
      cd -
    fi

# explicit email notifications don't play well with forks: don't use them
# default: committer and author get notifications
# we're now using defaults for everything, hence settings are commented
# out, left only for documentation purposes...

#notifications:
#  email:
#    on_success: change # default: change, may be: never
#    on_failure: always # default: always
